# Generated by Django 4.2.29 on 2026-03-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Titre du poste')),
                ('source', models.CharField(max_length=100, verbose_name='Source')),
                ('url', models.URLField(blank=True, max_length=1000, verbose_name='Lien')),
                ('sector', models.CharField(blank=True, choices=[('sante', 'Santé'), ('finance', 'Finance & Assurance'), ('industrie', 'Industrie & Manufacturing'), ('retail', 'Retail & E-commerce'), ('education', 'Éducation & Formation'), ('energie', 'Énergie & Environnement'), ('transport', 'Transport & Logistique'), ('administration', 'Administration publique'), ('autre', 'Autre')], max_length=50, verbose_name='Secteur')),
                ('skills', models.JSONField(default=list, verbose_name='Compétences détectées')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Localisation')),
                ('training_type_match', models.CharField(blank=True, choices=[('fondamentaux_ia', "Fondamentaux de l'IA et du Machine Learning"), ('data_science', 'Data Science & Analyse de données'), ('nlp', 'Traitement du langage naturel (NLP) & IA générative'), ('computer_vision', 'Vision par ordinateur'), ('ia_decisionnelle', 'IA décisionnelle & aide à la décision'), ('ethique_ia', "Éthique de l'IA & IA responsable"), ('ia_reglementaire', 'Réglementation IA (AI Act) & conformité'), ('deploiement_mlops', 'Déploiement & MLOps'), ('ia_metier', 'IA appliquée au métier (use cases sectoriels)'), ('management_ia', 'Management de projets IA & transformation')], max_length=30, verbose_name='Type de formation associé')),
                ('raw_description', models.TextField(blank=True, verbose_name='Description brute')),
                ('relevance_score', models.FloatField(default=0.0, verbose_name='Score de pertinence')),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Offre d'emploi",
                'verbose_name_plural': "Offres d'emploi",
                'ordering': ['-extracted_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Titre')),
                ('url', models.URLField(max_length=1000, unique=True, verbose_name='Lien')),
                ('source', models.CharField(max_length=200, verbose_name='Source')),
                ('summary', models.TextField(blank=True, verbose_name='Résumé')),
                ('sectors', models.JSONField(default=list, verbose_name='Secteurs concernés')),
                ('issues', models.JSONField(default=list, verbose_name='Enjeux concernés')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de publication')),
                ('relevance_score', models.FloatField(default=0.0, verbose_name='Score de pertinence')),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Article d'actualité",
                'verbose_name_plural': "Articles d'actualité",
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('linkedin', 'LinkedIn'), ('twitter', 'X (Twitter)'), ('other', 'Autre')], max_length=20, verbose_name='Plateforme')),
                ('content_summary', models.TextField(verbose_name='Résumé du contenu')),
                ('url', models.URLField(blank=True, max_length=1000, verbose_name='Lien')),
                ('hashtags', models.JSONField(default=list, verbose_name='Hashtags')),
                ('sector', models.CharField(blank=True, choices=[('sante', 'Santé'), ('finance', 'Finance & Assurance'), ('industrie', 'Industrie & Manufacturing'), ('retail', 'Retail & E-commerce'), ('education', 'Éducation & Formation'), ('energie', 'Énergie & Environnement'), ('transport', 'Transport & Logistique'), ('administration', 'Administration publique'), ('autre', 'Autre')], max_length=50, verbose_name='Secteur')),
                ('sentiment', models.CharField(choices=[('positive', 'Positif'), ('neutral', 'Neutre'), ('negative', 'Négatif')], default='neutral', max_length=10, verbose_name='Sentiment')),
                ('relevance_score', models.FloatField(default=0.0, verbose_name='Score de pertinence')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Signal social',
                'verbose_name_plural': 'Signaux sociaux',
                'ordering': ['-detected_at'],
            },
        ),
    ]
