# Generated by Django 4.2.29 on 2026-03-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('reddit', 'Reddit'), ('hackernews', 'Hacker News'), ('stackoverflow', 'Stack Overflow'), ('forum', 'Forum spécialisé'), ('other', 'Autre')], max_length=20, verbose_name='Plateforme')),
                ('title', models.CharField(max_length=500, verbose_name='Titre')),
                ('url', models.URLField(max_length=1000, unique=True, verbose_name='Lien')),
                ('content_summary', models.TextField(blank=True, verbose_name='Résumé')),
                ('subreddit', models.CharField(blank=True, max_length=100, verbose_name='Subreddit / catégorie')),
                ('score', models.IntegerField(default=0, verbose_name='Score / upvotes')),
                ('comments_count', models.IntegerField(default=0, verbose_name='Nombre de commentaires')),
                ('skills_mentioned', models.JSONField(default=list, verbose_name='Compétences mentionnées')),
                ('sector', models.CharField(blank=True, choices=[('sante', 'Santé'), ('finance', 'Finance & Assurance'), ('industrie', 'Industrie & Manufacturing'), ('retail', 'Retail & E-commerce'), ('education', 'Éducation & Formation'), ('energie', 'Énergie & Environnement'), ('transport', 'Transport & Logistique'), ('administration', 'Administration publique'), ('autre', 'Autre')], max_length=50, verbose_name='Secteur')),
                ('training_type_match', models.CharField(blank=True, choices=[('fondamentaux_ia', "Fondamentaux de l'IA et du Machine Learning"), ('data_science', 'Data Science & Analyse de données'), ('nlp', 'Traitement du langage naturel (NLP) & IA générative'), ('computer_vision', 'Vision par ordinateur'), ('ia_decisionnelle', 'IA décisionnelle & aide à la décision'), ('ethique_ia', "Éthique de l'IA & IA responsable"), ('ia_reglementaire', 'Réglementation IA (AI Act) & conformité'), ('deploiement_mlops', 'Déploiement & MLOps'), ('ia_metier', 'IA appliquée au métier (use cases sectoriels)'), ('management_ia', 'Management de projets IA & transformation')], max_length=30, verbose_name='Type de formation associé')),
                ('relevance_score', models.FloatField(default=0.0, verbose_name='Score de pertinence')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de publication')),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Post communautaire',
                'verbose_name_plural': 'Posts communautaires',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='TrendData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('google_trends', 'Google Trends'), ('github', 'GitHub Trending'), ('pypi', 'PyPI Downloads'), ('other', 'Autre')], max_length=20, verbose_name='Source')),
                ('keyword', models.CharField(max_length=200, verbose_name='Mot-clé / terme')),
                ('value', models.FloatField(default=0.0, verbose_name='Valeur (score / count)')),
                ('region', models.CharField(default='FR', max_length=50, verbose_name='Région')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Catégorie')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
                ('measured_at', models.DateTimeField(verbose_name='Date de mesure')),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Donnée de tendance',
                'verbose_name_plural': 'Données de tendances',
                'ordering': ['-measured_at'],
            },
        ),
        migrations.AlterField(
            model_name='socialsignal',
            name='platform',
            field=models.CharField(choices=[('linkedin', 'LinkedIn'), ('twitter', 'X (Twitter)'), ('reddit', 'Reddit'), ('hackernews', 'Hacker News'), ('other', 'Autre')], max_length=20, verbose_name='Plateforme'),
        ),
    ]
