# Generated by Django 4.2.29 on 2026-03-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0002_communitypost_trenddata_alter_socialsignal_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('weekly', 'Rapport hebdomadaire'), ('trend_analysis', 'Analyse de tendances'), ('sector_focus', 'Focus sectoriel')], max_length=20, verbose_name='Type')),
                ('title', models.CharField(max_length=300, verbose_name='Titre')),
                ('content', models.TextField(verbose_name='Contenu (Markdown)')),
                ('data_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Données source')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rapport IA',
                'verbose_name_plural': 'Rapports IA',
                'ordering': ['-generated_at'],
            },
        ),
    ]
