# Generated by Django 4.2.29 on 2026-03-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0003_aireport'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormationCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Nom')),
                ('provider', models.CharField(max_length=300, verbose_name='Organisme')),
                ('sector', models.CharField(blank=True, choices=[('sante', 'Santé'), ('finance', 'Finance & Assurance'), ('industrie', 'Industrie & Manufacturing'), ('retail', 'Retail & E-commerce'), ('education', 'Éducation & Formation'), ('energie', 'Énergie & Environnement'), ('transport', 'Transport & Logistique'), ('administration', 'Administration publique'), ('cyberdefense', 'Cyberdéfense & Défense'), ('autre', 'Autre')], max_length=50, verbose_name='Secteur')),
                ('training_type', models.CharField(blank=True, choices=[('executive', 'Executive Certificate'), ('diplome', 'Diplôme / Master'), ('certification', 'Certification'), ('courte', 'Formation courte'), ('mooc', 'MOOC / En ligne'), ('interne', 'Formation interne')], max_length=20, verbose_name='Type')),
                ('url', models.URLField(blank=True, max_length=1000, verbose_name='Lien')),
                ('price', models.CharField(blank=True, max_length=100, verbose_name='Prix')),
                ('format', models.CharField(blank=True, choices=[('presentiel', 'Présentiel'), ('distanciel', 'Distanciel'), ('hybride', 'Hybride'), ('elearning', 'E-learning')], max_length=20, verbose_name='Format')),
                ('duration', models.CharField(blank=True, max_length=100, verbose_name='Durée')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Formation IA',
                'verbose_name_plural': 'Formations IA',
                'ordering': ['-extracted_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicTender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Titre')),
                ('org', models.CharField(max_length=300, verbose_name='Organisme')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('budget', models.CharField(blank=True, max_length=100, verbose_name='Budget')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Date limite')),
                ('sector', models.CharField(blank=True, choices=[('sante', 'Santé'), ('finance', 'Finance & Assurance'), ('industrie', 'Industrie & Manufacturing'), ('retail', 'Retail & E-commerce'), ('education', 'Éducation & Formation'), ('energie', 'Énergie & Environnement'), ('transport', 'Transport & Logistique'), ('administration', 'Administration publique'), ('cyberdefense', 'Cyberdéfense & Défense'), ('autre', 'Autre')], max_length=50, verbose_name='Secteur')),
                ('url', models.URLField(blank=True, max_length=1000, verbose_name='Lien')),
                ('source', models.CharField(default='BOAMP', max_length=100, verbose_name='Source')),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Appel d'offres public",
                'verbose_name_plural': "Appels d'offres publics",
                'ordering': ['deadline'],
            },
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='sector',
            field=models.CharField(blank=True, choices=[('sante', 'Santé'), ('finance', 'Finance & Assurance'), ('industrie', 'Industrie & Manufacturing'), ('retail', 'Retail & E-commerce'), ('education', 'Éducation & Formation'), ('energie', 'Énergie & Environnement'), ('transport', 'Transport & Logistique'), ('administration', 'Administration publique'), ('cyberdefense', 'Cyberdéfense & Défense'), ('autre', 'Autre')], max_length=50, verbose_name='Secteur'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='sector',
            field=models.CharField(blank=True, choices=[('sante', 'Santé'), ('finance', 'Finance & Assurance'), ('industrie', 'Industrie & Manufacturing'), ('retail', 'Retail & E-commerce'), ('education', 'Éducation & Formation'), ('energie', 'Énergie & Environnement'), ('transport', 'Transport & Logistique'), ('administration', 'Administration publique'), ('cyberdefense', 'Cyberdéfense & Défense'), ('autre', 'Autre')], max_length=50, verbose_name='Secteur'),
        ),
        migrations.AlterField(
            model_name='socialsignal',
            name='sector',
            field=models.CharField(blank=True, choices=[('sante', 'Santé'), ('finance', 'Finance & Assurance'), ('industrie', 'Industrie & Manufacturing'), ('retail', 'Retail & E-commerce'), ('education', 'Éducation & Formation'), ('energie', 'Énergie & Environnement'), ('transport', 'Transport & Logistique'), ('administration', 'Administration publique'), ('cyberdefense', 'Cyberdéfense & Défense'), ('autre', 'Autre')], max_length=50, verbose_name='Secteur'),
        ),
    ]
