# Generated by Django 4.2.29 on 2026-08-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0004_formationcatalog_publictender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formationcatalog',
            name='skills_covered',
            field=models.JSONField(blank=True, default=list, verbose_name='Compétences couvertes'),
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='training_type_match',
            field=models.CharField(blank=True, choices=[('fondamentaux_ia', "Fondamentaux de l'IA et du Machine Learning"), ('data_science', 'Data Science & Analyse de données'), ('nlp', 'Traitement du langage naturel (NLP) & IA générative'), ('computer_vision', 'Vision par ordinateur'), ('ia_decisionnelle', 'IA décisionnelle & aide à la décision'), ('ethique_ia', "Éthique de l'IA & IA responsable"), ('ia_reglementaire', 'Réglementation IA (AI Act) & conformité'), ('deploiement_mlops', 'Déploiement & MLOps'), ('ia_metier', 'IA appliquée au métier (use cases sectoriels)'), ('management_ia', 'Management de projets IA & transformation'), ('innovation_digital', 'Innovation digitale & rôles IA émergents')], max_length=30, verbose_name='Type de formation associé'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='training_type_match',
            field=models.CharField(blank=True, choices=[('fondamentaux_ia', "Fondamentaux de l'IA et du Machine Learning"), ('data_science', 'Data Science & Analyse de données'), ('nlp', 'Traitement du langage naturel (NLP) & IA générative'), ('computer_vision', 'Vision par ordinateur'), ('ia_decisionnelle', 'IA décisionnelle & aide à la décision'), ('ethique_ia', "Éthique de l'IA & IA responsable"), ('ia_reglementaire', 'Réglementation IA (AI Act) & conformité'), ('deploiement_mlops', 'Déploiement & MLOps'), ('ia_metier', 'IA appliquée au métier (use cases sectoriels)'), ('management_ia', 'Management de projets IA & transformation'), ('innovation_digital', 'Innovation digitale & rôles IA émergents')], max_length=30, verbose_name='Type de formation associé'),
        ),
    ]
