# Generated by Django 4.2.29 on 2026-09-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0005_add_skills_covered_to_formationcatalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='company',
            field=models.CharField(blank=True, max_length=300, verbose_name='Entreprise'),
        ),
    ]
