# Generated by Django 4.2.29 on 2026-03-11 14:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Nom de l'entreprise")),
                ('sector', models.CharField(choices=[('sante', 'Santé'), ('finance', 'Finance & Assurance'), ('industrie', 'Industrie & Manufacturing'), ('retail', 'Retail & E-commerce'), ('education', 'Éducation & Formation'), ('energie', 'Énergie & Environnement'), ('transport', 'Transport & Logistique'), ('administration', 'Administration publique'), ('autre', 'Autre')], max_length=50, verbose_name="Secteur d'activité")),
                ('size', models.CharField(choices=[('tpe', 'TPE (< 10 salariés)'), ('pme', 'PME (10-249 salariés)'), ('eti', 'ETI (250-4999 salariés)'), ('ge', 'Grande entreprise (5000+ salariés)')], max_length=10, verbose_name='Taille')),
                ('location', models.CharField(max_length=255, verbose_name='Localisation')),
                ('email', models.EmailField(max_length=254, verbose_name='Email de contact')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Entreprise',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('ai_maturity', models.CharField(blank=True, choices=[('not_started', 'Pas commencé'), ('exploring', "Phase d'exploration"), ('pilot', 'Projets pilotes en cours'), ('deployed', 'IA déployée en production')], max_length=20, verbose_name='Niveau de maturité IA')),
                ('ai_tools', models.TextField(blank=True, verbose_name='Outils IA utilisés')),
                ('trained_employees', models.PositiveIntegerField(default=0, verbose_name='Nombre de collaborateurs formés')),
                ('budget', models.CharField(blank=True, choices=[('less_5k', 'Moins de 5 000 €'), ('5k_20k', '5 000 € - 20 000 €'), ('20k_50k', '20 000 € - 50 000 €'), ('50k_100k', '50 000 € - 100 000 €'), ('100k_plus', 'Plus de 100 000 €'), ('unknown', 'Non défini')], max_length=20, verbose_name='Budget formation IA')),
                ('preferred_format', models.CharField(blank=True, choices=[('presentiel', 'Présentiel'), ('distanciel', 'Distanciel'), ('hybride', 'Hybride'), ('elearning', 'E-learning')], max_length=20, verbose_name='Format préféré')),
                ('priority_skills', models.JSONField(blank=True, default=list, verbose_name='Compétences prioritaires')),
                ('free_text', models.TextField(blank=True, verbose_name='Besoins spécifiques non couverts')),
                ('is_complete', models.BooleanField(default=False)),
                ('current_step', models.PositiveIntegerField(default=1)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='survey.company')),
            ],
            options={
                'verbose_name': 'Réponse au questionnaire',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingNeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_type', models.CharField(choices=[('fondamentaux_ia', "Fondamentaux de l'IA et du Machine Learning"), ('data_science', 'Data Science & Analyse de données'), ('nlp', 'Traitement du langage naturel (NLP) & IA générative'), ('computer_vision', 'Vision par ordinateur'), ('ia_decisionnelle', 'IA décisionnelle & aide à la décision'), ('ethique_ia', "Éthique de l'IA & IA responsable"), ('ia_reglementaire', 'Réglementation IA (AI Act) & conformité'), ('deploiement_mlops', 'Déploiement & MLOps'), ('ia_metier', 'IA appliquée au métier (use cases sectoriels)'), ('management_ia', 'Management de projets IA & transformation')], max_length=30, verbose_name='Type de formation')),
                ('need_level', models.CharField(choices=[('none', 'Aucun'), ('low', 'Faible'), ('moderate', 'Modéré'), ('high', 'Élevé'), ('critical', 'Critique')], default='none', max_length=10, verbose_name='Niveau de besoin')),
                ('people_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de personnes à former')),
                ('urgency', models.CharField(blank=True, choices=[('3months', 'Moins de 3 mois'), ('3_6months', '3 à 6 mois'), ('6_12months', '6 à 12 mois'), ('12months_plus', 'Plus de 12 mois')], max_length=15, verbose_name='Urgence')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_needs', to='survey.surveyresponse')),
            ],
            options={
                'verbose_name': 'Besoin en formation',
                'unique_together': {('response', 'training_type')},
            },
        ),
        migrations.CreateModel(
            name='CriticalIssueRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('competences', 'Pénurie de compétences IA'), ('donnees', 'Qualité et accès aux données'), ('ethique', 'Éthique et biais algorithmiques'), ('reglementation', 'Conformité réglementaire (AI Act)'), ('investissement', "Coûts d'investissement et ROI"), ('resistance', 'Résistance au changement'), ('souverainete', 'Souveraineté numérique'), ('cybersecurite', "Cybersécurité liée à l'IA"), ('environnement', "Impact environnemental de l'IA"), ('emploi', 'Transformation des emplois')], max_length=30, verbose_name='Enjeu')),
                ('rank', models.PositiveIntegerField(verbose_name='Classement (1 = plus prioritaire)')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_rankings', to='survey.surveyresponse')),
            ],
            options={
                'verbose_name': 'Classement des enjeux',
                'ordering': ['rank'],
                'unique_together': {('response', 'issue_type')},
            },
        ),
    ]
